/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWatchlistRouteImport } from './routes/_authenticated/watchlist'
import { Route as AuthenticatedRisksRouteImport } from './routes/_authenticated/risks'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedMarketRouteImport } from './routes/_authenticated/market'
import { Route as AuthenticatedLearnRouteImport } from './routes/_authenticated/learn'
import { Route as AuthenticatedDiaryRouteImport } from './routes/_authenticated/diary'
import { Route as AuthenticatedBondsRouteImport } from './routes/_authenticated/bonds'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthYandexCallbackRouteImport } from './routes/auth/yandex/callback'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'
import { Route as AuthenticatedMarketSymbolRouteImport } from './routes/_authenticated/market/$symbol'
import { Route as AuthenticatedLearnGlossaryRouteImport } from './routes/_authenticated/learn/glossary'
import { Route as AuthenticatedLearnSlugRouteImport } from './routes/_authenticated/learn/$slug'
import { Route as AuthenticatedBondsSymbolRouteImport } from './routes/_authenticated/bonds/$symbol'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWatchlistRoute = AuthenticatedWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRisksRoute = AuthenticatedRisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketRoute = AuthenticatedMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLearnRoute = AuthenticatedLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiaryRoute = AuthenticatedDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBondsRoute = AuthenticatedBondsRouteImport.update({
  id: '/bonds',
  path: '/bonds',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthYandexCallbackRoute = AuthYandexCallbackRouteImport.update({
  id: '/auth/yandex/callback',
  path: '/auth/yandex/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMarketSymbolRoute =
  AuthenticatedMarketSymbolRouteImport.update({
    id: '/$symbol',
    path: '/$symbol',
    getParentRoute: () => AuthenticatedMarketRoute,
  } as any)
const AuthenticatedLearnGlossaryRoute =
  AuthenticatedLearnGlossaryRouteImport.update({
    id: '/glossary',
    path: '/glossary',
    getParentRoute: () => AuthenticatedLearnRoute,
  } as any)
const AuthenticatedLearnSlugRoute = AuthenticatedLearnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedLearnRoute,
} as any)
const AuthenticatedBondsSymbolRoute =
  AuthenticatedBondsSymbolRouteImport.update({
    id: '/$symbol',
    path: '/$symbol',
    getParentRoute: () => AuthenticatedBondsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/ai': typeof AuthenticatedAiRoute
  '/bonds': typeof AuthenticatedBondsRouteWithChildren
  '/diary': typeof AuthenticatedDiaryRoute
  '/learn': typeof AuthenticatedLearnRouteWithChildren
  '/market': typeof AuthenticatedMarketRouteWithChildren
  '/overview': typeof AuthenticatedOverviewRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/risks': typeof AuthenticatedRisksRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/bonds/$symbol': typeof AuthenticatedBondsSymbolRoute
  '/learn/$slug': typeof AuthenticatedLearnSlugRoute
  '/learn/glossary': typeof AuthenticatedLearnGlossaryRoute
  '/market/$symbol': typeof AuthenticatedMarketSymbolRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/yandex/callback': typeof AuthYandexCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/ai': typeof AuthenticatedAiRoute
  '/bonds': typeof AuthenticatedBondsRouteWithChildren
  '/diary': typeof AuthenticatedDiaryRoute
  '/learn': typeof AuthenticatedLearnRouteWithChildren
  '/market': typeof AuthenticatedMarketRouteWithChildren
  '/overview': typeof AuthenticatedOverviewRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/risks': typeof AuthenticatedRisksRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/bonds/$symbol': typeof AuthenticatedBondsSymbolRoute
  '/learn/$slug': typeof AuthenticatedLearnSlugRoute
  '/learn/glossary': typeof AuthenticatedLearnGlossaryRoute
  '/market/$symbol': typeof AuthenticatedMarketSymbolRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/yandex/callback': typeof AuthYandexCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/bonds': typeof AuthenticatedBondsRouteWithChildren
  '/_authenticated/diary': typeof AuthenticatedDiaryRoute
  '/_authenticated/learn': typeof AuthenticatedLearnRouteWithChildren
  '/_authenticated/market': typeof AuthenticatedMarketRouteWithChildren
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/risks': typeof AuthenticatedRisksRoute
  '/_authenticated/watchlist': typeof AuthenticatedWatchlistRoute
  '/_authenticated/bonds/$symbol': typeof AuthenticatedBondsSymbolRoute
  '/_authenticated/learn/$slug': typeof AuthenticatedLearnSlugRoute
  '/_authenticated/learn/glossary': typeof AuthenticatedLearnGlossaryRoute
  '/_authenticated/market/$symbol': typeof AuthenticatedMarketSymbolRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/yandex/callback': typeof AuthYandexCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/ai'
    | '/bonds'
    | '/diary'
    | '/learn'
    | '/market'
    | '/overview'
    | '/portfolio'
    | '/profile'
    | '/risks'
    | '/watchlist'
    | '/bonds/$symbol'
    | '/learn/$slug'
    | '/learn/glossary'
    | '/market/$symbol'
    | '/auth/google/callback'
    | '/auth/yandex/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/ai'
    | '/bonds'
    | '/diary'
    | '/learn'
    | '/market'
    | '/overview'
    | '/portfolio'
    | '/profile'
    | '/risks'
    | '/watchlist'
    | '/bonds/$symbol'
    | '/learn/$slug'
    | '/learn/glossary'
    | '/market/$symbol'
    | '/auth/google/callback'
    | '/auth/yandex/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/ai'
    | '/_authenticated/bonds'
    | '/_authenticated/diary'
    | '/_authenticated/learn'
    | '/_authenticated/market'
    | '/_authenticated/overview'
    | '/_authenticated/portfolio'
    | '/_authenticated/profile'
    | '/_authenticated/risks'
    | '/_authenticated/watchlist'
    | '/_authenticated/bonds/$symbol'
    | '/_authenticated/learn/$slug'
    | '/_authenticated/learn/glossary'
    | '/_authenticated/market/$symbol'
    | '/auth/google/callback'
    | '/auth/yandex/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  AuthYandexCallbackRoute: typeof AuthYandexCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/watchlist': {
      id: '/_authenticated/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthenticatedWatchlistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/risks': {
      id: '/_authenticated/risks'
      path: '/risks'
      fullPath: '/risks'
      preLoaderRoute: typeof AuthenticatedRisksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/market': {
      id: '/_authenticated/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AuthenticatedMarketRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn': {
      id: '/_authenticated/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diary': {
      id: '/_authenticated/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof AuthenticatedDiaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bonds': {
      id: '/_authenticated/bonds'
      path: '/bonds'
      fullPath: '/bonds'
      preLoaderRoute: typeof AuthenticatedBondsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/yandex/callback': {
      id: '/auth/yandex/callback'
      path: '/auth/yandex/callback'
      fullPath: '/auth/yandex/callback'
      preLoaderRoute: typeof AuthYandexCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/market/$symbol': {
      id: '/_authenticated/market/$symbol'
      path: '/$symbol'
      fullPath: '/market/$symbol'
      preLoaderRoute: typeof AuthenticatedMarketSymbolRouteImport
      parentRoute: typeof AuthenticatedMarketRoute
    }
    '/_authenticated/learn/glossary': {
      id: '/_authenticated/learn/glossary'
      path: '/glossary'
      fullPath: '/learn/glossary'
      preLoaderRoute: typeof AuthenticatedLearnGlossaryRouteImport
      parentRoute: typeof AuthenticatedLearnRoute
    }
    '/_authenticated/learn/$slug': {
      id: '/_authenticated/learn/$slug'
      path: '/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof AuthenticatedLearnSlugRouteImport
      parentRoute: typeof AuthenticatedLearnRoute
    }
    '/_authenticated/bonds/$symbol': {
      id: '/_authenticated/bonds/$symbol'
      path: '/$symbol'
      fullPath: '/bonds/$symbol'
      preLoaderRoute: typeof AuthenticatedBondsSymbolRouteImport
      parentRoute: typeof AuthenticatedBondsRoute
    }
  }
}

interface AuthenticatedBondsRouteChildren {
  AuthenticatedBondsSymbolRoute: typeof AuthenticatedBondsSymbolRoute
}

const AuthenticatedBondsRouteChildren: AuthenticatedBondsRouteChildren = {
  AuthenticatedBondsSymbolRoute: AuthenticatedBondsSymbolRoute,
}

const AuthenticatedBondsRouteWithChildren =
  AuthenticatedBondsRoute._addFileChildren(AuthenticatedBondsRouteChildren)

interface AuthenticatedLearnRouteChildren {
  AuthenticatedLearnSlugRoute: typeof AuthenticatedLearnSlugRoute
  AuthenticatedLearnGlossaryRoute: typeof AuthenticatedLearnGlossaryRoute
}

const AuthenticatedLearnRouteChildren: AuthenticatedLearnRouteChildren = {
  AuthenticatedLearnSlugRoute: AuthenticatedLearnSlugRoute,
  AuthenticatedLearnGlossaryRoute: AuthenticatedLearnGlossaryRoute,
}

const AuthenticatedLearnRouteWithChildren =
  AuthenticatedLearnRoute._addFileChildren(AuthenticatedLearnRouteChildren)

interface AuthenticatedMarketRouteChildren {
  AuthenticatedMarketSymbolRoute: typeof AuthenticatedMarketSymbolRoute
}

const AuthenticatedMarketRouteChildren: AuthenticatedMarketRouteChildren = {
  AuthenticatedMarketSymbolRoute: AuthenticatedMarketSymbolRoute,
}

const AuthenticatedMarketRouteWithChildren =
  AuthenticatedMarketRoute._addFileChildren(AuthenticatedMarketRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedBondsRoute: typeof AuthenticatedBondsRouteWithChildren
  AuthenticatedDiaryRoute: typeof AuthenticatedDiaryRoute
  AuthenticatedLearnRoute: typeof AuthenticatedLearnRouteWithChildren
  AuthenticatedMarketRoute: typeof AuthenticatedMarketRouteWithChildren
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRisksRoute: typeof AuthenticatedRisksRoute
  AuthenticatedWatchlistRoute: typeof AuthenticatedWatchlistRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedBondsRoute: AuthenticatedBondsRouteWithChildren,
  AuthenticatedDiaryRoute: AuthenticatedDiaryRoute,
  AuthenticatedLearnRoute: AuthenticatedLearnRouteWithChildren,
  AuthenticatedMarketRoute: AuthenticatedMarketRouteWithChildren,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRisksRoute: AuthenticatedRisksRoute,
  AuthenticatedWatchlistRoute: AuthenticatedWatchlistRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  AuthYandexCallbackRoute: AuthYandexCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
